// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvr8mOhbE0Z7T4Zw3PHTqM_FmtkE5J0LQ',
    appId: '1:536112508108:web:c89e44c156e0ede7a7a669',
    messagingSenderId: '536112508108',
    projectId: 'bus-buddy-a2849',
    authDomain: 'bus-buddy-a2849.firebaseapp.com',
    storageBucket: 'bus-buddy-a2849.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRtrZuvPyJPX4RS-uwSvCpxMuL8n6I1w',
    appId: '1:536112508108:android:43c261869b578bb4a7a669',
    messagingSenderId: '536112508108',
    projectId: 'bus-buddy-a2849',
    storageBucket: 'bus-buddy-a2849.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxnMb1S4v1FDmrI3oUEVMv-Slaft1_IEQ',
    appId: '1:536112508108:ios:b46de89426d220d0a7a669',
    messagingSenderId: '536112508108',
    projectId: 'bus-buddy-a2849',
    storageBucket: 'bus-buddy-a2849.appspot.com',
    iosBundleId: 'com.example.busBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxnMb1S4v1FDmrI3oUEVMv-Slaft1_IEQ',
    appId: '1:536112508108:ios:54d0d6c7c007d92ba7a669',
    messagingSenderId: '536112508108',
    projectId: 'bus-buddy-a2849',
    storageBucket: 'bus-buddy-a2849.appspot.com',
    iosBundleId: 'com.example.busBuddy.RunnerTests',
  );
}
